# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
   vmImage: 'ubuntu-latest' 

stages:
- stage: Build and Push
  displayName: Build docker image and push to container registry
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'gr5ma23b-padimaster'
        repository: 'frontend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'