resources:
  pipelines:
  - pipeline: production
    source: production-ci
    trigger: true

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure for Students(c82dd837-5e13-427c-b590-13569d8ac5f7)'
      appType: 'webAppContainer'
      WebAppName: 'task-maker'
      DockerNamespace: 'gr5ma23b.azurecr.io'
      DockerRepository: 'frontend'
      DockerImageTag: 'latest'
      AppSettings: '-Port 3000'