# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
   vmImage: 'ubuntu-latest' 

variables:
  imageName: 'frontend'
  containerRegistry: 'gr5ma23b.azurecr.io'
  tag: 'latest'

stages:
- stage: Build
  displayName: Build docker image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: '$(imageName)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: Push
  displayName: Push to azure container registry
  jobs:
  - job: Push
    displayName: Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Login'
      inputs:
        containerRegistry: '$(containerRegistry)'
        command: 'login'
    - task: Docker@2
      displayName: Push docker image
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(imageName)'
        command: 'push'
        tags: |
          $(tag)