trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureContainerApps@1
    inputs:
      appSourcePath: '$(Build.SourcesDirectory)/src'
      azureSubscription: 'Azure for Students'
      acrName: 'frontend'
      containerAppName: 'task-maker'
      resourceGroup: 'GR5MA23B'